apiVersion: v1
kind: Service
metadata:
  name: firstproject-service
spec:
  selector:
    app: firstproject
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # 외부에서 접근할 NodePort 번호 (30000~32767 사이에서 선택)
