name: CI - Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64] # Multi-platform 지원

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Setup QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Docker Buildx 설치 (multi-platform 빌드를 위한 도구)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. GitHub Container Registry 로그인
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Docker 이미지 빌드 및 푸시 (GitHub Container Registry)
      - name: Build and Push Docker Image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}  # Multi-platform 빌드
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/firstproject

      # 6. Optional: 빌드 성공 알림
      - name: Notify build success
        if: success()
        run: echo "Docker image build and push to GitHub Container Registry successful!"
